[phases.install]
cmds = [
  "composer install --optimize-autoloader --no-scripts --no-interaction --ignore-platform-req=ext-gd --ignore-platform-req=ext-exif"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
