[variables]
NIXPACKS_PHP_VERSION = "8.2"

[phases.setup]
nixPkgs = ["php82", "php82Extensions.gd", "php82Extensions.exif"]

[phases.install]
cmds = [
  "install-php-extensions tokenizer intl curl pdo calendar openssl mbstring pdo_mysql ctype dom fileinfo filter hash pcre session xml redis gd exif",
  "composer install --optimize-autoloader --no-interaction"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
