[variables]
NIXPACKS_PHP_VERSION = "8.2"
NIXPACKS_PHP_EXTENSIONS = "gd,exif"

[phases.setup]
nixPkgs = ["php82Extensions.gd", "php82Extensions.exif"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
